import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import Head from 'next/head'
import styles from './DefaultLayout.module.scss'
import { Container } from '@chakra-ui/react'

const DefaultLayout = ({ children }: any) => {
  return (
    <>
    <Container maxW={'full'} bg={'brand.base'} color={'brand.primary'}>
      <Head>
        <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='8xl' centerContent>
        <Navbar/>
         <Container maxW='4xl'>
            <main className={styles.main}>
              { children }
            </main>
          </Container>
        <Footer/>
      </Container>
    </Container>
    </>
  )
}

export default DefaultLayout;