import { Navbar } from "@/components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import Head from 'next/head'
import styles from './DefaultLayout.module.scss'

const DefaultLayout = ({ children }: any) => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        {children}
      </main>
      <Footer />

    </div>
  )
}

export default DefaultLayout;